### PR TITLE
Remove redundant path variables

### LINKED ISSUE #60: Redundant paths definitions
Paths for tools from the `molprobity` and `ATSAS` suites are explicitly defined through environment variables. I think this is redundant since there is a generic and OS-independent way of using the PATH environment variable. 

```
ATSAS="" 
Molprobity_ramalyze=""
Molprobity_molprobity=""
Molprobity_clashscore=""
Molprobity_rotalyze=""
wkhtmltopdf=""

```

https://github.com/salilab/IHMValidation/blob/0bb8ad2a0c74924eafaa5871e9658df13becca5f/master/pyext/src/validation/molprobity.py#L65

https://github.com/salilab/IHMValidation/blob/0bb8ad2a0c74924eafaa5871e9658df13becca5f/master/pyext/src/validation/molprobity.py#L81

https://github.com/salilab/IHMValidation/blob/0bb8ad2a0c74924eafaa5871e9658df13becca5f/master/pyext/src/validation/molprobity.py#L97

https://github.com/salilab/IHMValidation/blob/0bb8ad2a0c74924eafaa5871e9658df13becca5f/master/pyext/src/validation/molprobity.py#L112

Moreover, in case of ATSAS it's a little bit misleading, since only `datcmp` used and not the whole ATSAS package. 

https://github.com/salilab/IHMValidation/blob/0bb8ad2a0c74924eafaa5871e9658df13becca5f/master/pyext/src/validation/sas.py#L345-L346

### PR DESCRIPTION
**Pull request by aozalevsky**
Fixes #60

### CODE REVIEW

**Comment by aozalevsky** [comment]
@benmwebb this PR fails due to a mismatch of bokeh versions which was fixed in #65. I don't think that I should duplicate the change in this branch too.

**Comment by benmwebb** [comment]
No, it is failing due to a flake test. I rebased it (closed and reopened) after applying your bokeh fix.

**Comment by aozalevsky** [comment]
oh, I see. It is still strange though because it fails on files unaffected by the change. Did you change the testing workflow recently? I don't see any commits. 

I can fix flake8 errors in this branch, but do not want to mix apples and oranges in one place.

**Comment by benmwebb** [comment]
Probably it's just a newer version of flake8 that is being more strict. Totally up to you whether you want to address these issues in this PR or in a separate one.

**Pull request merged**
